### PR TITLE
Bring v3.1.5 up to date

### PR DESCRIPTION
**Pull request by rhc54**
@dsolt Please check to see if I caught everything needed for support of unknown nspaces.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey The VERSION info had to be reset due to the change in Allocation_request signature - would you mind double-checking it?

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
Version increment looks correct to me.

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by rhc54** [comment]
bot:ibm:xvercheck:retest

**Pull request merged**
