### PR TITLE
First cut of Sphinx / ReadTheDocs docs

### PR DESCRIPTION
**Pull request by jsquyres**
Took all content from README, README.ms, INSTALL, HACKING, and EXCEPTIONS and put them in various files in the docs/ subdirectory. Made token man pages for several PMIx topics.

Also copied a bunch of stock material from the Open MPI Sphinx docs (e.g., several pages from
https://github.com/open-mpi/ompi/tree/main/docs/developers).

Much editing still needs to be done; this commit is mainly about the configure/build infrastructure (e.g., setting up Sphinx and getting "make dist" to work properly).  The RST documentation content that is provided is still incomplete.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@rhc54 This PR is now ready for review.

**Comment by rhc54** [comment]
Hmmm...you won't get thru CI with this unless we make some changes:
```shell
#########################################################################
#
# make dist is disabled due to the following packages: Sphinx/Documentation
#
#########################################################################
```

**Comment by jsquyres** [comment]
@rhc54 I just fixed up some "TODO"-ish comments to make them more blatant / easy to find for those who build on the content from this PR.

For the `make dist` failure, that's intentional: if you build a "dist" tarball, you'll need to have Sphinx.  Specifically:

1. `configure` looks for Sphinx
2. If you `make all`:
    * If HTML+nroff docs are already present and up-to-date (i.e., the source `.rst` files have not been modified), per normal `make` rules, no action will be taken (i.e., Sphinx will not be invoked) because there's no need to re-build the HTML+nroff docs.
    * If the HTML+nroff docs are either not present or out of date (e.g., source `.rst` files have been modified), then:
        * If Sphinx was found by `configure`, Sphinx will be invoked to (re-)build the HTML+nroff docs.
        * If Sphinx was not found by `configure`, the docs will not be (re-)built.
3. If you `make install`:
    * If HTML+nroff docs are present, they will be installed (regardless of whether `configure` found Sphinx or not)
    * If HTML+nroff docs are not present, they will not be installed.
4. If you `make dist`:
    * If `configure` did not find Sphinx, it will error / abort.
    * If `configure` did find Sphinx, HTML+nroff docs will be generated (per `make all`) and included in the tarball.

The goals here are:

1. End users who build from a distribution tarball will have pre-built HTML+nroff docs available.  Hence:
    * They do not need to have Sphinx.
    * They will have HTML+nroff docs installed.
2. Developers who build from a git clone can have Sphinx available or not.
    * If they have Sphinx available, the HTML+nroff docs will be built (if needed) and installed.
    * If they don't have Sphinx available:
        * They won't get HTML+nroff docs built
        * If there's no previously-built HTML+nroff docs available, they won't be installed
        * They can't run `make dist`

**Comment by jsquyres** [comment]
Huzzah! It wasn't hard to update the MLNX Github action to install Sphinx, and therefore to enable `make dist` to succeed.

**Pull request merged**
