### PR TITLE
Roll to rc4

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jjhursey** [comment]
I'm not sure this is correct, or at least I need some more information before I understand the versioning change.

In Issue #1633 the original issue was that rc1 moved `libpmix.so.2` to `libpmix.so.3` by mistake, and the request was to then bump the `.so` numbering on the other `.so`'s that we ship. That I think I get.

However, since we fixed the mistake and `libpmix.so.2` is the correct `c` value then I don't think we want to change the other `.so`'s for this generation of the library (v3.x series). Otherwise, we signal a major change in those `.so`'s (similar to Issue #1624). Maybe we just change the revision number for the v3.x series.

In the PMIx 4.x series, we can update the `c` levels on all of the `.so`'s since they are different than the v3.x versions.

**Comment by rhc54** [comment]
IF you follow the discussion on #1633 plus some over on the OMPI side over time, you'll see that the absolute value of the ```c``` level is irrelevant - what the linkers focus on is the ```c-a``` result as that sets the SOVERSION number. In this case, we neglected to shift that difference to track the ```c-a``` of the main libpmix library. This causes a problem for packagers as it breaks the SOVERSION alignment of the two (common and main) libraries.

When we go to v4, we need to bump the ```c``` value such that ```c-a``` increments, thus signaling a change in the overall SOVERSION number.

**Comment by rhc54** [comment]
I believe we have to make the move now, not later. As things stand, the common/dstore lib is associated with PMIx v2.x, not v3, which is why @amckinstry pointed out that it was causing downstream problems.

**Comment by jjhursey** [comment]
Ok. I'm willing to go that way. I think we need a note on the release page as a heads up for anyone that might care.

**Comment by rhc54** [comment]
Okay, I added those two bullets plus one for #1640. Once you okay that one, we should be good to do this and roll rc4.

**Comment by jjhursey** [comment]
Let's hold this PR until we get a resolution on the discussion item [here](https://github.com/openpmix/openpmix/issues/1633#issuecomment-586649031)

**Comment by rhc54** [comment]
Per the discussion, we will not fix the common SOVERSION value until the PMIx v4 release.

**Pull request merged**
