### PR TITLE
build: Import and use external Autoconf repo

### PR DESCRIPTION
**Pull request by bwbarrett**
Start using our external repo of Autoconf macros shared across the Open MPI, OpenPMIx, and PRRTE projects. For now, only move OAC_ASSERT_LITERAL and  OAC_CHECK_PACKAGE, plus their dependencies, but we expect to move more over time. This will help manage the divergence in macros between the three projects (we already had significant divergence in CHECK_PACKAGE after less than a year).

Signed-off-by: Brian Barrett <bbarrett@amazon.com>

### CODE REVIEW

**Comment by bwbarrett** [comment]
I'm pretty sure the test failures are due to the submodule not getting checked out.  I didn't realize that the openpmix autogen.pl didn't have the submodule state check that is in ompi.  I'll port that over so that I can prove my theory.

**Comment by rhc54** [comment]
Yeah, we didn't port that check over because PMIx didn't have submodules. Looks like your supposition has been proven - the submodule is not getting checked out.

**Comment by bwbarrett** [comment]
@rhc54 I'm not going to have time to track down the CI updates required this week; any chance you can take a look?

**Comment by rhc54** [comment]
yeah, i can try - not all are within my reach, but i'll see what can be done

**Comment by jjhursey** [comment]
I updated the backend IBM scripts. Let's see if it helps.
bot:ibm:retest

**Comment by rhc54** [comment]
I've got the other tests (minux Mlnx) updated here: https://github.com/openpmix/pmix-tests/pull/146

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
IBM CI has been updated and seems to be running fine now.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
LANL CI will need to be updated - can happen later.

**Comment by hppritcha** [comment]
something strange is going on.  I updated the script jenkins is suppose to run but jenkins isn't picking it up.

**Pull request merged**
