### PR TITLE
Enable multi-server tests

### PR DESCRIPTION
**Pull request by artpol84**
Signed-off-by: Artem Polyakov <artpol84@gmail.com>

### CODE REVIEW

**Comment by artpol84** [comment]
@rhc54 I see "Merging is blocked" (restricted to authorized users). Can I get added?

**Comment by rhc54** [comment]
I don't think it is actually blocked - I think it is still requiring GPG signed commits and that is why an admin has to do the merge. I can relax that requirement - not sure we really care, though it was a worthwhile experiment.

**Comment by artpol84** [comment]
So I need to enable GPG signature of commits?

**Comment by rhc54** [comment]
No, I just removed that requirement - you should be able to commit now

**Comment by rhc54** [comment]
Sorry for the delay - took me a bit to remember where that setting exists 😄

**Comment by artpol84** [comment]
From Mellanox CI
```
+ eval timeout -s SIGKILL 1m ./pmix_test -s 2 -n 2 --job-fence -o '$OUTDIR/out'
++ timeout -s SIGKILL 1m ./pmix_test -s 2 -n 2 --job-fence -o /github/workspace/out/out
==26678== [1576097450.037337] pmix_test.c:main: Test SUCCEEDED!
==26664== [1576097450.037823] test_server.c:server_finalize: Test finished OK!
==26664== [1576097450.038871] pmix_test.c:main: Test SUCCEEDED!
```

**Comment by artpol84** [comment]
Still saying I'm not authorized :(

**Comment by artpol84** [comment]
xversion script hasn't picked it up though:
```
Server : /home/pmixer/scratch/pmix-master/test
Command: cd /home/pmixer/scratch/pmix-master/test ; timeout --preserve-status -k 35 30 ./pmix_test -s 1 -n 2 --job-fence -e /home/pmixer/scratch/pmix-master/test/pmix_client
Status : 0
-----> : Test output (Not shown)
-----> : Run simptest Make Check
Make Check: /home/pmixer/scratch/pmix-master/test/pmix_client
Server : /home/pmixer/scratch/pmix-master/test
Command: cd /home/pmixer/scratch/pmix-master/test ; timeout --preserve-status -k 35 30 ./pmix_test -s 1 -n 2 --job-fence -c -e /home/pmixer/scratch/pmix-master/test/pmix_client
Status : 0
-----> : Test output (Not shown)
```

**Comment by artpol84** [comment]
As https://github.com/openpmix/openpmix/pull/1552 was only merged into the master. Do we need it to propagate it to other branches for xversion script to work?

**Comment by rhc54** [comment]
Hmmm...maybe the change in authorization settings only takes affect on new PRs? I'll commit for you. We will need to propagate things, but may have to look at where it needs to go.

**Comment by artpol84** [comment]
@rhc54 I didn't mean this one is ready to go :).
As I indicated, the cross-version hasn't run with -s 2.
@jjhursey do we need to change xversion script to enable it?

**Comment by artpol84** [comment]
It looks like it is:
https://github.com/openpmix/openpmix/pull/1563

But I don't have a write access to pmix-test as well :(

**Comment by rhc54** [comment]
Yeah, there are still things to adjust since we moved all these repos. I went ahead and made the change over there so it is now enabled.

**Pull request merged**
