### PR TITLE
Fix compiler behavior tests

### PR DESCRIPTION
**Pull request by bwbarrett**
Found a couple of broken configure tests while cleaning up other issues.

### CODE REVIEW

**Review by rhc54 — APPROVED** [review]
Interesting...

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by bwbarrett** [comment]
@jjhursey and @rhc54 can you help me understand the prrte output test that's failing?  I can't imagine how it relates to this PR?

**Comment by rhc54** [comment]
It doesn't - we have a problem in the "signature" being used to evaluate the output. I'm trying to update it now

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Pull request merged**
