### PR TITLE
Port multi server fixes to v3.1

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
@karasevb, please take a look

**Comment by artpol84** [comment]
@jjhursey is there a way to see the output for failed cases?

**Comment by rhc54** [comment]
You can't get the output in the report logs, but you can see the error output in the test "details" themselves. Here is an example:
```shell
Make Check: /home/pmixer/scratch/pmix-v3.1/test/pmix_client
Server : /home/pmixer/scratch/pmix-master/test
Command: cd /home/pmixer/scratch/pmix-master/test ; timeout --preserve-status -k 35 30 ./pmix_test -s 2 -n 2 --job-fence -e /home/pmixer/scratch/pmix-v3.1/test/pmix_client
Status : 4 ***FAILED***
-----> : Test output
==59532== ERROR [test_fence.c:386:test_job_fence]: smoky_nspace-0:1: PMIx_Get_nb failed: 0 from smoky_nspace-0:0, key=key-f100:0
==59532== ERROR [test_fence.c:388:test_job_fence]: smoky_nspace-0:1: PMIx_Get failed: ERROR
==59531== ERROR [test_fence.c:386:test_job_fence]: smoky_nspace-0:0: PMIx_Get_nb failed: 0 from smoky_nspace-0:1, key=key-f100:0
==59531== ERROR [test_fence.c:388:test_job_fence]: smoky_nspace-0:0: PMIx_Get failed: ERROR
```
You can also execute the ```xversion.py``` test by hand and specify the exact combination of client and server versions (plus constrain the tests to just the "make check" set) so you only look at the piece under investigation. See ```xversion.py --help``` for the cmd line options.

**Comment by karasevb** [comment]
`./pmix_test -s 2 -n 2 --job-fence` this test leads to crash:
```C
(gdb) bt
#0  __strncmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:1859
#1  0x00007f319f7e3ca1 in fetch_nodeinfo (key=0x0, tgt=0x7f31980051f0, info=0x7f3198015e00, ninfo=139851141811488, kvs=0x7f319e7967f0) at gds_hash.c:2273
#2  0x00007f319f7e6552 in hash_fetch (proc=0x7f319e7964a0, scope=4 '\004', copy=false, key=0x0, qualifiers=0x7f3198015e00, nqual=139851141811488, kvs=0x7f319e7967f0) at gds_hash.c:2602
#3  0x00007f31a1763699 in _satisfy_request (nptr=0x7f31980008c0, rank=0, cd=0x7f3198015df0, cbfunc=0x7f31a1736d43 <get_cbfunc>, cbdata=0x7f31980155c0, local=0x0) at server/pmix_server_get.c:750
#4  0x00007f31a1765616 in pmix_pending_resolve (nptr=0x7f31980008c0, rank=0, status=0, lcd=0x7f3198015b20) at server/pmix_server_get.c:943
#5  0x00007f31a1766c60 in _process_dmdx_reply (fd=-1, args=4, cbdata=0x7f3198014770) at server/pmix_server_get.c:1121
#6  0x00007f31a14876dd in event_process_active_single_queue (base=base@entry=0x114c080, activeq=0x114c4d0, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1646
#7  0x00007f31a1487def in event_process_active (base=0x114c080) at event.c:1738
#8  event_base_loop (base=0x114c080, flags=1) at event.c:1961
#9  0x00007f31a176a9ed in progress_engine (obj=0x114c000) at runtime/pmix_progress_threads.c:232
#10 0x00007f31a1250182 in start_thread (arg=0x7f319e797700) at pthread_create.c:312
#11 0x00007f31a0f7d47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

It looks like memory corruption: `ninfo=139851141811488`. I'm investigating this.

**Comment by karasevb** [comment]
Commit 4e90d30f70efc75af97fa3900eb56b2e84a98c36 should fix the segfault problem.
@artpol84 please merge my PR:https://github.com/artpol84/pmix/pull/2 opened against this PR.

**Comment by artpol84** [comment]
Done, let’s see

**Comment by karasevb** [comment]
Results without fix:
```C
Run ***FAILED***: master -> v3.1  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: master -> v3.1  [-s 2 -n 2 --job-fence -c -e ]
Run ***FAILED***: v3.1 -> v3.1  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: v3.1 -> v3.1  [-s 2 -n 2 --job-fence -c -e ]
Run ***FAILED***: v3.1 -> v2.2  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: v3.1 -> fix_ms  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: fix_ms -> master  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: fix_ms -> v3.1  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: fix_ms -> v3.1  [-s 2 -n 2 --job-fence -c -e ]
Run ***FAILED***: fix_ms -> v2.2  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: fix_ms -> fix_ms  [-s 2 -n 2 --job-fence -e ]
```
Results with fix:
```C
Run ***FAILED***: master -> v3.1  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: master -> v3.1  [-s 2 -n 2 --job-fence -c -e ]
Run ***FAILED***: v3.1 -> master  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: v3.1 -> v3.1  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: v3.1 -> v3.1  [-s 2 -n 2 --job-fence -c -e ]
Run ***FAILED***: v3.1 -> v2.2  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: fix_ms -> v3.1  [-s 2 -n 2 --job-fence -e ]
Run ***FAILED***: fix_ms -> v3.1  [-s 2 -n 2 --job-fence -c -e ]
```

As we see `fix_ms` with the ninfo fix has no fails with branches. I suppose when it is merged to v3.1 all failures should disappear.

**Comment by artpol84** [comment]
@rhc54 , @jjhursey food to go IMO

**Comment by artpol84** [comment]
@karasevb, will this work well with previous branches?

**Comment by rhc54** [comment]
Very nice - thanks!

**Pull request merged**
