### PR TITLE
Update Github actions to use submodules

### PR DESCRIPTION
**Pull request by jjhursey**
Using https://github.com/marketplace/actions/checkout-submodules

### CODE REVIEW

**Comment by rhc54** [comment]
Yeah, this is probably the right approach. My changes to `pmix-tests` didn't accomplish anything, so I'll revert them.

**Comment by jjhursey** [comment]
You can probably keep them in pmix-tests since it's going to be the 'right thing to do' if a user is looking at the code.

**Comment by rhc54** [comment]
I'll leave them in for now so long as they "do no harm" - can revert later if needed

**Review by rhc54 — APPROVED** [review]

**Comment by rhc54** [comment]
so why are the IBM ones failing "during PREP"?

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
Looks like a corner case. I just pushed a fix. Should be good now.

**Pull request merged**
