### PR TITLE
Added test_v2 directory for new version of test suite (#2)

### PR DESCRIPTION
**Pull request by cpshereda**
This is the start of the new PMIx test suite per @artpol84 's guidance. 

This initial version only includes pmix_test.c and all its dependencies, and nothing else, in a new subdirectory of test called test_v2. 

For now it is built using a custom Makefile and is not touched by configure, so it will not be part of the regular build process, nor enabled, for now. The idea is that for a period of time it will be run independent of/in parallel to the existing test suite.

### CODE REVIEW

**Comment by artpol84** [comment]
@rhc54 @jjhursey 

These changes are not touching any working pieces of the PMIx and introduce a new directory where the new test system will evolve. From my perspective it is good to go.

BTW I'm still not able to merge into PMIx master. I don't have this issue with OMPI anymore. @rhc54 can you look again into that? Maybe we can use this PR to debug my access rights.

**Comment by rhc54** [comment]
Not quite sure what to try here - you are a member of the "Developers" team, and that team has "write" access to the repo. So everything looks okay from the GitHub perspective. Are you seeing the "merge" button grayed out?

**Comment by rhc54** [comment]
I think I found it - see if the button is green for you now

**Comment by artpol84** [comment]
Thanks!

**Pull request merged**
