### PR TITLE
Update VERSION

### PR DESCRIPTION
**Pull request by rhc54**
The branch has moved past the v3.1.5 tag

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
bot:ibm:xver:retest

**Comment by rhc54** [comment]
bot:ibm:xvertool:retest

**Comment by rhc54** [comment]
bot:ibm:xvercheck:retest

**Pull request merged**
