### PR TITLE
gds:shmem: Checkpoint mostly server-side work.

### PR DESCRIPTION
**Pull request by samuelkgutierrez**
Checkpoint mostly server-side work storing info objects into a
shared-memory backing store.

Signed-off-by: Samuel K. Gutierrez <samuel@lanl.gov>

### CODE REVIEW

**Comment by samuelkgutierrez** [comment]
Looks like the `dmodex` test is failing. I'm not sure why.

**Comment by rhc54** [comment]
@awlauria I'm not sure if we still have a problem in the test - I don't see anything immediately wrong in the output, but it just stopped. If I read it correctly, it only ran for 13 seconds? Could you please investigate?

**Comment by rhc54** [comment]
@samuelkgutierrez Nothing to do with this change - we may still need some debugging of the test itself.

**Comment by awlauria** [comment]
@rhc54 the test isn't timing out, it's hitting more PMIx_Get() failures.

```

15:44:45 Client ns prterun-94d8d5204348-144@1 rank 0: PMIx_Get prterun-94d8d5204348-144@1-0-remote failed: NOT-FOUND
15:44:45 prterun-94d8d5204348-144@1:21 Remote value for prterun-94d8d5204348-144@1:0 successfully retrieved
```
I wonder if the timeout in the test just needs to be increased?

**Comment by awlauria** [comment]
The output of that test is a little...verbose...I opened up https://github.com/openpmix/pmix-tests/pull/123 to clean that up.

Should make it easier to see what went wrong.

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by samuelkgutierrez** [comment]
Thank you @awlauria and @rhc54.

**Pull request merged**
