### PR TITLE
Replaced PMIx_Notify_Event with cbfunc call in errhandler

### PR DESCRIPTION
**Pull request by cpshereda**
Done to match recent change in original test repo and fix apparent bug.

### CODE REVIEW

**Review by rhc54 — APPROVED** [review]
Yeah, it wouldn't be too happy otherwise!

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Review by artpol84 — APPROVED** [review]

**Comment by artpol84** [comment]
Thank you, @cpshereda

**Comment by jjhursey** [comment]
Cross version hit an odd configure issue that I've not seen before. Let's retry:
bot:ibm:xver:retest
bot:ibm:xvertool:retest
bot:ibm:xvercheck:retest

And PRRTE hit the intermittent IO issue with the debug tests see https://github.com/openpmix/prrte/issues/1046:
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
The xversion failure is consistent, but I don't see anything in this PR that would cause it - and other PRs are passing version.
I wonder if the branch is just a little out of date or something.

I added notes to the CI Bots page on to to reproduce locally with the same Docker container that CI is running:
 * https://github.com/openpmix/openpmix/wiki/CI-Bots-Information-Page#ibm-ci-cross-version-triggers

**Comment by cpshereda** [comment]
Odd. It shouldn't be out of date at all, I rebased before pushing this, so the commit before this one is a merge from Ralph dated Wednesday July 21 with SHA 7294e3d.

**Comment by rhc54** [comment]
The problem is that the container being used doesn't have hwloc in it, and we now require it. I had changed that Dockerfile in the github repo, but obviously only in the master branch. I'll backport that change to the earlier branches.

**Comment by rhc54** [comment]
Looking at this more closely, I changed the Mellanox container - which is still working correctly. I don't immediately see where to change the IBM containers. @jjhursey is that something in the pmix-tests repo? Or something you have to do over there?

**Comment by jjhursey** [comment]
The location of the source for the cross version container image is on the wiki [here](https://github.com/openpmix/openpmix/wiki/CI-Bots-Information-Page#ibm-ci-cross-version-triggers).
It is basically a wrapper around the `pmix-tests/crossversion/xversion.py` [see here](https://github.com/jjhursey/pmix-xver-tester/blob/master/bin/run-xversion.sh#L83-L99)

Looking at that script [here](https://github.com/openpmix/pmix-tests/blob/master/crossversion/xversion.py#L176-L208) it looks like it is passing in hwloc to the OpenPMix build.

**Comment by rhc54** [comment]
Yeah, it's your Dockerfile that needs to be updated - it doesn't have `hwloc hwloc-devel` in the `yum install` list.

**Comment by rhc54** [comment]
Actually, it looks like you are building it separately and not using the rpm versions. No idea of why it is failing then - it fails because it isn't finding hwloc. 🤷‍♂️

**Comment by jjhursey** [comment]
I tested building via the cross version process locally and it built ok. Let me have CI check it out and I'll copy that over to see if the git checkout somehow messed things up.
bot:ibm:xver:retest

**Comment by jjhursey** [comment]
Ok I tracked this down to the branch name (of all things). The `v2` in the branch name ` pmix-pr-testv2_errhandler_fix` causes it to use [this](https://github.com/openpmix/pmix-tests/blob/master/crossversion/xversion.py#L187) configure which doesn't have hwloc since we didn't need it for the `v2` branch. That regex needs fixing.

I posted a PR here that I tested locally to fix the problem:
 * https://github.com/openpmix/pmix-tests/pull/105

**Comment by rhc54** [comment]
Wow, that's arcane - thx!

**Comment by jjhursey** [comment]
bot:ibm:xver:retest
bot:ibm:xvertool:retest
bot:ibm:xvercheck:retest

**Comment by cpshereda** [comment]
@jjhursey what's the status of this now?

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Comment by rhc54** [comment]
should be good to go - just rerunning the prrte test as those signatures have been updated, so it should pass now

**Pull request merged**
