### PR TITLE
Support fix for OMPI Github issue #11532

### PR DESCRIPTION
**Pull request by qkoziol**
Support fix in OMPI by creating an installed header file for the frameworks that OpenPMIX is built with, so that any legacy framework parameters can be translated by OMPI.

Addresses issue https://github.com/open-mpi/ompi/issues/11532, and supports OMPI PR: https://github.com/open-mpi/ompi/pull/11854

### CODE REVIEW

**Comment by qkoziol** [comment]
bot:retest

**Comment by rhc54** [comment]
I'm confused - we already output an array of all the framework names precisely for this purpose. It is used by PMIx and PRRTE. Contents:
```c
char *pmix_framework_names[] = {
    "bfrops",
    "gds",
    "pcompress",
    "pdl",
    "pfexec",
    "pgpu",
    "pif",
    "pinstalldirs",
    "plog",
    "pmdl",
    "pnet",
    "preg",
    "prm",
    "psec",
    "psensor",
    "psquash",
    "pstat",
    "pstrg",
    "ptl",
    "mca",
    NULL
};
```
Why is that not sufficient?

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by qkoziol** [comment]
> I'm confused - we already output an array of all the framework names precisely for this purpose. It is used by PMIx and PRRTE. Contents:
> 
> ```c
> char *pmix_framework_names[] = {
>     "bfrops",
>     "gds",
>     "pcompress",
>     "pdl",
>     "pfexec",
>     "pgpu",
>     "pif",
>     "pinstalldirs",
>     "plog",
>     "pmdl",
>     "pnet",
>     "preg",
>     "prm",
>     "psec",
>     "psensor",
>     "psquash",
>     "pstat",
>     "pstrg",
>     "ptl",
>     "mca",
>     NULL
> };
> ```
> 
> Why is that not sufficient?

Ah, I didn't think that header was being installed, but I now see it in ${PREFIX}/include/pmix/src/include.  I'll get that a try and may be able to avoid this new header.

**Comment by qkoziol** [comment]
> > I'm confused - we already output an array of all the framework names precisely for this purpose. It is used by PMIx and PRRTE. Contents:
> > ```c
> > char *pmix_framework_names[] = {
> >     "bfrops",
> >     "gds",
> >     "pcompress",
> >     "pdl",
> >     "pfexec",
> >     "pgpu",
> >     "pif",
> >     "pinstalldirs",
> >     "plog",
> >     "pmdl",
> >     "pnet",
> >     "preg",
> >     "prm",
> >     "psec",
> >     "psensor",
> >     "psquash",
> >     "pstat",
> >     "pstrg",
> >     "ptl",
> >     "mca",
> >     NULL
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why is that not sufficient?
> 
> Ah, I didn't think that header was being installed, but I now see it in ${PREFIX}/include/pmix/src/include. I'll give that a try and may be able to avoid this new header.

Using  pmix/src/include/pmix_frameworks.h works, closing this PR.

**Pull request closed without merging**
