### PR TITLE
util/pmix_shmem.c: toggle builtin atomics routine based on configure

### PR DESCRIPTION
**Pull request by wenduwan**
`./configure ... --disable-builtin-atomics` is currently broken. This patch fixes that.

### CODE REVIEW

**Comment by wenduwan** [comment]
@rhc54 @samuelkgutierrez Could you please take a look? Thanks!

**Comment by samuelkgutierrez** [comment]
Thank you, @wenduwan. Based on my testing last week, I don't feel confident that the old way I had implemented reference counting was correct, especially on system architectures that can aggressively reorder memory operations.

Why do you disable built-in atomics? I'm curious because this change makes me a little nervous given how touchy this part of the code has been. Maybe we can figure out another approach.

**Comment by lrbison** [comment]
This is an alternative: https://github.com/openpmix/openpmix/pull/3075

Which is to use c11 atomics or GCC builtin atomics based on configure options, and implement the same `pmix_atomic_fetch_add_32` style functions using c11 atomics.

**Comment by wenduwan** [comment]
@lrbison Thanks! Closing this PR in favor of https://github.com/openpmix/openpmix/pull/3075

**Comment by wenduwan** [comment]
@samuelkgutierrez This was caught in our internal testing matrix, not that we want to disable builtin atomics.

**Pull request closed without merging**
