### PR TITLE
Add the PMIx Standard version level to the version string

### PR DESCRIPTION
**Pull request by jjhursey**
* PMIx Standard version can be adjusted in the VERSION file
 * `OpenPMIx 4.1.0a1 (PMIx Standard: 4.0)`

### CODE REVIEW

**Comment by jjhursey** [comment]
The Mellanox CI seems to be failing all of the tests with an error like:
```
++ '[' '4
41
0' -ge 31 ']'
/entrypoint.sh: line 94: [: 4
41
0: integer expression expected
```
Without being able to see the output file it is parsing I'm not sure what might be going on here. It might be related to the version string - it's hard to tell.

Can @amaslenn or someone from Mellanox (@artpol84 do you know the right person to flag here?) take a look?

**Comment by jjhursey** [comment]
Per teleconf - let's see if we can add the git hash to the output on git builds - not tarball.

**Comment by jjhursey** [comment]
I added the git revision to the output string for git checked out builds. The string is generated from `git describe` inside of the `config/pmix_get_version.sh` script.

 * For git repos it looks like:
   - `OpenPMIx 4.1.0a1, repo rev: v1.1.3-2710-gc3f68e00 (PMIx Standard: 4.0)`
 * For non git repos (e.g., tarballs) it looks like:
   - `OpenPMIx 4.1.0a1 (PMIx Standard: 4.0)`

**Comment by jjhursey** [comment]
I poked around at the Mellanox script a bit, and think I know what the problem is. It's the evaluation of this:
 * https://github.com/openpmix/openpmix/blob/master/.github/actions/mlnx/entrypoint.sh#L48

On master without this PR it evaluates to `41` with this PR it evaluates to `4 41 0` because we defined `std_major` and `std_minor` which are picked up by this expression. If we change the expression per below then we are fine:
```diff
- pmix_ver=`cat VERSION | grep "major=" | cut -d "=" -f 2``cat VERSION | grep "minor=" | cut -d "=" -f 2`
+ pmix_ver=`cat VERSION | grep "^major=" | cut -d "=" -f 2``cat VERSION | grep "^minor=" | cut -d "=" -f 2`
```

I just pushed that change to this PR which should resolve the issue.

**Review by abouteiller — APPROVED** [review]

**Review by rhc54 — APPROVED** [review]

**Pull request merged**
