### PR TITLE
WIP: Generating a pkg-config file

### PR DESCRIPTION
**Pull request by mdorier**
This PR adds the generation and installation of a pmix.pc file which would allow the PMIx libs and cflags (as well as its dependencies) to be found by pkg-config.

At the moment the generated pmix.pc file contains hard-coded dependencies to hwloc and libevent, so it is appropriate for use only when PMIx is installed with hwloc and libevent support. These dependencies are hard-coded in configure.ac (lines 262 to 279).

The next step would be to make these variables depend on what is actually needed (i.e. not add hwloc if it's not enabled, add the libev libraries instead of libevent if PMIx is compiled with libev, etc.)

### CODE REVIEW

**Comment by jjhursey** [comment]
ok to test

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Comment by rhc54** [comment]
@mdorier Could you please sign off your commit? You just need to add a line at the end of the commit message "Signed-off-by: name \<email\>"

**Comment by mdorier** [comment]
> @mdorier Could you please sign off your commit? You just need to add a line at the end of the commit message "Signed-off-by: name <email>"

Done!

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Comment by rhc54** [comment]
@mdorier I updated your PR to include the configure logic results in PC_REQUIRES. Thanks again for the contribution!

**Comment by mdorier** [comment]
@rhc54 Thanks, but be careful: libev doesn't seem to have a pkg-config file, so it won't be found by pkg-config. You should add the necessary `-L/path/to/libev/lib` and `-lev` in `PC_PRIVATE_LIBS`.

**Comment by rhc54** [comment]
Ah, thanks - I was wondering about that but didn't know how to check. I'll update

**Comment by rhc54** [comment]
@mdorier Done!

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
Can you cherry-pick this to the `v3.1` branch? It's looking like we will be releasing a 3.1.6 in the near-ish future and we can include this in that release.

**Pull request merged**
