### PR TITLE
build: Support hwloc and libevent cobuild

### PR DESCRIPTION
**Pull request by bwbarrett**
Add ability for PMIx to find hwloc and libevent packages which are
built at the same time as PMIx, such as third party dependencies
in an MPI package.  This is a slight change on the existing
embedded PMIx support, in that it does not assume that PMIx itself
is being built embedded in another library, only that some of its
dependencies may be built at the same time as PMIx.

Signed-off-by: Brian Barrett <bbarrett@amazon.com>

### CODE REVIEW

**Comment by bwbarrett** [comment]
> @bwbarrett I have no issue with these changes. However, I would like to eliminate embedded mode once you have made the corresponding changes to OMPI as nobody else is embedding PMIx, and I would like to avoid anyone doing so in the future.

That makes sense.  I left both modes to make it easier to decouple updates to PMIx and OMPI.  Once the changes to use the cobuild code are in OMPI, we can update PMIx as well.

**Comment by bwbarrett** [comment]
I can't see an obvious failure with IBM CI.  Any hints?

**Comment by rhc54** [comment]
Yeah, just committed a fix that should resolve the problem - the timeout on the tests was just skirting the edge of failure.

**Comment by rhc54** [comment]
bot:ibm:xvercheck:retest

**Pull request merged**
