### PR TITLE
v4.2: Bring in some updates from master.

### PR DESCRIPTION
**Pull request by awlauria**
[Don't limit message size unless requested](https://github.com/openpmix/openpmix/commit/bd93ac0af480434a77b71d449ef55b810d5f16b3)[](https://github.com/rhc54)[](https://github.com/awlauria) 
 
[Fix the "client" example](https://github.com/openpmix/openpmix/commit/ccd6627fe57941e5dd7840a8beb166c156cca8e7)[](https://github.com/rhc54)[](https://github.com/awlauria) 
 
[Fix memcpy size in pmix_bfrops_base_copy_darray().](https://github.com/openpmix/openpmix/commit/d5e4e6dab040ac543c9b29748a18e635edfb0a0f)[](https://github.com/samuelkgutierrez)[](https://github.com/awlauria)

### CODE REVIEW

**Comment by rhc54** [comment]
I was just getting ready to do an update - thx for taking it on! You are, however, missing one that should come across:

[build: Delay adding DELAYED_LIBS even more](https://github.com/openpmix/openpmix/commit/fbc2513882d0a83a4c59bd0fd34b5c58fa811eaa)

Also, I'm assuming we want the "query ABI" support as well for the Totalview guys when working with OMPI v5. @jjhursey would you concur?

**Comment by awlauria** [comment]
Yeah I was not sure on that one, I can add if here if we want it for OMPI v5.

**Comment by awlauria** [comment]
Thanks - added the delayed libs commit.

**Review by jjhursey — APPROVED** [review]

**Review by rhc54 — APPROVED** [review]
Sounds reasonable - thx again1

**Pull request merged**
