### PR TITLE
avoid warning on void function return

### PR DESCRIPTION
**Pull request by naughtont3**
Signed-off-by: Thomas Naughton <naughtont@ornl.gov>

### CODE REVIEW

**Comment by rhc54** [comment]
looks like IBM CI failed for some of these - I'd try rerunning those specific ones.

**Comment by naughtont3** [comment]
gcc 5.5.0 on old ubuntu 16.04 machine

```
beaker: (avoidwarn-hwloc)$ gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by rhc54** [comment]
Interesting - wasn't getting it on some other versions, including gcc 4.8.5. Thanks for catching it!

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Pull request merged**
