### PR TITLE
Protect job control from NULL results param

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest
bot:ibm:ibm:xvertool:retest

**Comment by jjhursey** [comment]
bot:ibm:xvertool:retest

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Comment by rhc54** [comment]
@jjhursey It feels like the rendezvous race condition is getting worse - maybe we should add some debug to that connection logic in ptl/tcp and just cycle a PR with it?

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Pull request merged**
