### PR TITLE
Added erroneously excluded test_fence_basic.c test case

### PR DESCRIPTION
**Pull request by cpshereda**
Thanks for catching this, @rhc54.

### CODE REVIEW

**Review by rhc54 — APPROVED** [review]
Thx!

**Comment by cpshereda** [comment]
Can't figure out why the LANL-CI is still failing with the same problem.

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:ibm:retest

**Comment by hppritcha** [comment]
hmm,  bad day for IBM CI, try again
bot:ibm:retest

**Pull request merged**
