### PR TITLE
delete use of `PMIX_CHECK_BROKEN_QSORT` refs #2375

### PR DESCRIPTION
**Pull request by naughtont3**
Signed-off-by: Thomas Naughton <naughtont@ornl.gov>

### CODE REVIEW

**Comment by rhc54** [comment]
Ouch - thanks for catching it. Interesting that it didn't trip anyone/anywhere else 🤷‍♂️

**Comment by naughtont3** [comment]
Yes, that worried me too.  The gcc thing is likely a red hearing, just part of other things going on today.  But surprised this did not cause a problem anywhere else when using the v4.1/v4.2 branches or rc5 tag.  

Also not sure how this slipped by when master has is correctly.

**Comment by rhc54** [comment]
> Also not sure how this slipped by when master has is correctly.

I still see it in master...actually thought you were fixing it there first 😄

**Comment by naughtont3** [comment]
Doh!  Too many branches/machines.  I guess I didn't have a fresh master on desktop.

**Comment by naughtont3** [comment]
Well, that does make me feel a little better. I was very confused as to why it was only on the branches.  Turns out it was just me that was confused.  Added the master PR.

**Comment by rhc54** [comment]
Thx! Much appreciated

**Pull request merged**
