### PR TITLE
A ci test

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
@jjhursey I have the client and tool xversion working now - only "make_check" remains.

**Comment by rhc54** [comment]
bot:ibm:xvercheck:retest

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
`make check` passed! 🎺 🎆

**Pull request closed without merging**
