### PR TITLE
Fix backward compatibility issue when running a 3.2 and later server …

### PR DESCRIPTION
**Pull request by dsolt**
…with a 3.1 and earlier client.

Signed-off-by: David Solt <dsolt@us.ibm.com>

### CODE REVIEW

**Comment by dsolt** [comment]
Will need to some eyes on this, but I there is definitely some issue with put/get between ranks on the same node as evidenced by this test case with a 3.2 server and a 3.1 client (or master server and 3.1 client):

**Comment by jjhursey** [comment]
@dsolt Ralph adjusted some backward compatibility in PR #1838 in this function. I don't know if it helps, but you might want to try the new v3.2 branch and see if it fixes the issue you were seeing.

**Comment by jjhursey** [comment]
Ping. What the status of this PR?

**Comment by rhc54** [comment]
FWIW: this test passes on current master

**Comment by rhc54** [comment]
I verified this also works with v3.2 server and v3.1 client, so I believe this is complete

**Pull request closed without merging**
