### PR TITLE
(v4.2) avoid python setup.py installdir error

### PR DESCRIPTION
**Pull request by naughtont3**
Fixes issue of ``make install`` failing with python bindings enabled.

### CODE REVIEW

**Comment by naughtont3** [comment]
bot:ibm:xver:retest

**Comment by naughtont3** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
@naughtont3 This needs to be a cherry-pick of the commit from master - can you please redo it that way?

**Comment by rhc54** [comment]
Closing as I've included the cherry-pick in https://github.com/openpmix/openpmix/pull/3053

**Pull request closed without merging**
