### PR TITLE
Add the local reference ID to iof/pull request

### PR DESCRIPTION
**Pull request by rhc54**
Refs https://github.com/openpmix/openpmix/issues/2010

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey Got this on the cross-version checks:
```text
If you see this page then something went wrong with IBM's CI test on your PR (e.g., network connectivity issue).
```
Something wrong with those nodes?

**Comment by rhc54** [comment]
bot:ibm:xver:retest

**Comment by rhc54** [comment]
bot:ibm:xvertool:retest

**Comment by rhc54** [comment]
bot:ibm:xvercheck:retest

**Comment by jjhursey** [comment]
From the internal Jenkins logs, it looks like the IBM CI machine experienced a file system (and then network) hiccup. It seems to be resolve now. Sorry about that.

**Pull request merged**
