### PR TITLE
Some cleanup of IOF output

### PR DESCRIPTION
**Pull request by rhc54**
No longer directly output stdout/stderr - add them to the event
list for output. This helps us deal with the case where the std
file descriptors are getting blocked/metered. Add a counter to
track the number of times we attempt to output to a given sink
and abort if we exceed that count - helps avoid deadlock where
we simply cannot get the output to go. Also, don't try to "join"
the progress thread when we stop it as this can hang if we are
in an event we cannot get out of.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Comment by rhc54** [comment]
Something weird is going on with the Mellanox CI - the failures make no sense as they are simply repeats of other tests that passed. Let's try simplifying the CI script.

**Comment by rhc54** [comment]
@hppritcha @cpshereda I am unable to get your "test_v2" code to compile on my machines. The include paths are making some unfortunate assumptions about where libevent resides, and no matter how I edit the Makefile, I cannot find a way to satisfy the code. Could someone please make this work in a more generic setting?

**Comment by cpshereda** [comment]
Yes, I'll work on it later today.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Comment by rhc54** [comment]
bot:mellanox:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Pull request closed without merging**
