### PR TITLE
Fix issue 1598

### PR DESCRIPTION
**Pull request by dsolt**
Set the correct value of local for new trackers.

### CODE REVIEW

**Comment by dsolt** [comment]
WIP, will sign off if we want to use this.

**Comment by artpol84** [comment]
Interestingly, I recall that recently there was a fix in that area. Was it incorrect?

**Comment by rhc54** [comment]
@artpol84 No, the fix was correct - this was a proposal from @dsolt that we noted was incorrect, as was the one I had originally proposed. This PR should be closed.

**Comment by artpol84** [comment]
But why the code seems different that at the time of https://github.com/openpmix/openpmix/pull/1564?

**Comment by artpol84** [comment]
In particular, the following is missing:

```C
    if (trk->nlocal == nptr->nprocs) {
        trk->local = true;
    }
```

**Comment by artpol84** [comment]
It was there at the time:
https://github.com/openpmix/openpmix/pull/1564/files#diff-cf506bd64a1184a18c5ad19dfdb8913dL506

**Comment by rhc54** [comment]
Because @dsolt was looking at the original file. My original proposal was done in parallel. He asked which one was correct, and the conclusion was "neither". So I started over again - took a few days to work thru it all and straighten it out, but it now passes @jjhursey's multi-node CI for PRRTE. We had been routinely failing it before this go-around, plus we discovered problems when working on the dmodex issue (which I am still working to finalize).

**Pull request closed without merging**
