### PR TITLE
Revert tests to symlinks to ensure correct timeout value

### LINKED ISSUE #1889: 3.2 test/run_testsXX.pl.in should be symlinks not copies
Hey guys the 3.2.0 tarball uses tests with the old timeouts (~30secs) instead of the new, longer timeouts (~500secs) so we're getting some test failures on a few arches that have slower vm's used for building rpms.  As I look at the 3.2 tree, I notice right away that the `tests/run_testsXX.pl.in` files are _copies_ not symlinks as in 3.1, each with the old timeout.

Ref #1834 

Cheers, Phil

```
=====================================
   pmix 3.2.0: test/test-suite.log
=====================================
# TOTAL: 14
# PASS:  12
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
.. contents:: :depth: 2
FAIL: run_tests06.pl
====================
/usr/bin/timeout --preserve-status -k 35 30  ./pmix_test -n 4 --job-fence -c 2>&1
CODE 36608
FAIL run_tests06.pl (exit status: 143)
FAIL: run_tests07.pl
====================
/usr/bin/timeout --preserve-status -k 35 30  ./pmix_test -n 4 --job-fence 2>&1
CODE 36608
FAIL run_tests07.pl (exit status: 143)
============================================================================
```

### PR DESCRIPTION
**Pull request by rhc54**
Fixes #1889

Thanks to @pkovacs for the report

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Review by jjhursey — APPROVED** [review]
Too bad this wasn't caught during the rc period for 3.2.0.

**Comment by jjhursey** [comment]
bot:ibm:xver:retest
bot:ibm:xvertool:retest
bot:ibm:xvercheck:retest

**Comment by jjhursey** [comment]
Huh - the cross-version is legitimately failing with this PR now. It looks like some data corruption in the tests.

**Review by jjhursey — COMMENTED** [review]
See comment about the cross-version failures

**Comment by rhc54** [comment]
Not data corruption - you are missing some changes that went into master to properly handle the cross-version case for the v3.2.x series. I'll try to bring them over.

**Comment by rhc54** [comment]
You were actually correct - it was memory corruption, but it was a simple error in the test itself and not in the code base 😄

**Comment by jjhursey** [comment]
Thanks for fixing that!

**Pull request merged**
