### PR TITLE
GitHub Action for xversion testing

### PR DESCRIPTION
**Pull request by jjhursey**
- Move the following cross-version CI tests to GitHub Actions
   - `IBM CI (Cross-version: Client)`
   - `IBM CI (Cross-version: Tool)`
   - `IBM CI (Cross-version: make check)`

### CODE REVIEW

**Comment by jjhursey** [comment]
The second step in moving the PMIx Cross Version CI from the IBM machines
 - The first step is generating the containers: https://github.com/openpmix/pmix-tests/pull/111
 - Moving these to GitHub Actions should make them more responsive and reliable for the community.
 - Additionally, the CI is now fully in control of the community making it easier for them to adjust them as needed.

**Comment by jjhursey** [comment]
This is marked as WIP because we have a failure in the Cross Version client test on master that we are trying to track down. It only occurs in the container (at the moment anyway).

**Comment by jjhursey** [comment]
Now that https://github.com/openpmix/openpmix/pull/2439 is merged the cross-version container builds via GitHub Actions (which uses Docker on x86) pass cleanly.

These three CI tests will run in GitHub Actions:
```
OpenPMIx Cross Version Testing / xversion-client (pull_request)
OpenPMIx Cross Version Testing / xversion-tool (pull_request)
OpenPMIx Cross Version Testing / xversion-check (pull_request)
```

And replace the IBM ppc64le versions, respectively:
```
IBM CI (Cross-version: Client)
IBM CI (Cross-version: Tool)
IBM CI (Cross-version: make check)
```

Information on how to re-run these GitHub Actions has been added to the following wiki page:
 * https://github.com/openpmix/openpmix/wiki/CI-Bots-Information-Page
 * Direct link: https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs

The container used for testing is generated/refreshed once a week via GitHub Actions in the pmix-tests PR https://github.com/openpmix/pmix-tests/pull/111

**Review by rhc54 — APPROVED** [review]
I'm no expert, but it looks okay and it seems to be working.

Thanks for doing this!

**Comment by jjhursey** [comment]
No problem. I'll leave the IBM xversion CI in place for another week just in case we see any oddness with the new actions. Then I'll disable the IBM xversion CI allowing the GitHub Actions to take that role.

**Pull request merged**
