### PR TITLE
Address pedantic compiler warnings

### PR DESCRIPTION
**Pull request by samuelkgutierrez**
This commit changes how the pmix_regattr_input_t dictionary is created.
It addresses a 'defined but not used' warning (or error) that is
generated when pedantic developer flags are enabled by
--enable-devel-check.

In particular, construct_dictionary.py now generates two files:
pmix_dictionary.h and pmix_dictionary.c. The previous methodology
generated a single file named dictionary.h. Please note that we changed
the name of the generated files to more closely match OpenPMIx's file
naming convention. Since the dictionary's symbol is now exported, we
also changed its name to pmix_dictionary. Additionally, the generated
array is now declared as const to match its intended usage.

construct_dictionary.py was also modified to address some warnings
generated by flake8. These changes were trivial.

Signed-off-by: Samuel K. Gutierrez <samuel@lanl.gov>

### CODE REVIEW

**Comment by rhc54** [comment]
That's...pretty bizarro. What compiler is this?

**Comment by rhc54** [comment]
I hit the following error:
```text
In file included from pmix_dictionary.c:6:
/Users/rhc/pmix/sam/src/include/pmix_dictionary.h:23:5: error: no newline at end of file [-Werror,-Wnewline-eof]
    
```
Compiler: Apple clang version 13.1.6 (clang-1316.0.21.2.3)

**Comment by rhc54** [comment]
It also seems weird that we wind up with:
```c
#define PMIX_INDEX_BOUNDARY  511
```
at the end of _both_ the `.h` and the `.c` file. Should it just be in the `.h` file?

**Comment by samuelkgutierrez** [comment]
> That's...pretty bizarro. What compiler is this?

The compiler I'm using is `gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0`.  I believe the problem was that a static variable was defined in a compilation unit and not used there.

**Comment by samuelkgutierrez** [comment]
> > > That's...pretty bizarro. What compiler is this?
> > 
> > 
> > The compiler I'm using is `gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0`. I believe the problem was that a static variable was defined in a compilation unit and not used there.
> > **Edit:** I understand that it was used within the source that was including it, but most modern (picky) compilers will complain about this sort of thing.
> 
> That's why I was asking - we've been building this with `--enable-devel-check` in a variety of environments, and this is the first one that complained. I grok the reason - just interesting that we never hit it before now. I have no issues with the change but wanted to understand the conditions under which it now appeared.

Interesting. And with this compiler I still have a few minor updates that I will push soon to successfully build with `--enable-devel-check`. Perhaps my compiler doesn't trust me, so its heart has become hardened and bitter with time.

**Comment by rhc54** [comment]
> Interesting. And with this compiler I still have a few minor updates that I will push soon to successfully build with `--enable-devel-check`. Perhaps my compiler doesn't trust me, so its heart has become hardened and bitter with time.

Yeah, who knows what lurks in the heart of a compiler? 😄 Are you going to add those updates here? If so, I'm happy to leave this open for a bit until you do. I just hit one on `gcc 8.5` in the `dmodex.c` example:
```text
dmodex.c: In function ‘main’:
dmodex.c:145:46: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
     snprintf(proc.nspace, PMIX_MAX_NSLEN, "%s",  myproc.nspace);
                                              ^
dmodex.c:145:5: note: ‘snprintf’ output between 1 and 256 bytes into a destination of size 255
     snprintf(proc.nspace, PMIX_MAX_NSLEN, "%s",  myproc.nspace);
```
Should be:
```c
PMIX_LOAD_NSPACE(proc.nspace, myproc.nspace);
```
to avoid the complaint.

**Comment by samuelkgutierrez** [comment]
> > Interesting. And with this compiler I still have a few minor updates that I will push soon to successfully build with `--enable-devel-check`. Perhaps my compiler doesn't trust me, so its heart has become hardened and bitter with time.
> 
> Yeah, who knows what lurks in the heart of a compiler? 😄 Are you going to add those updates here? If so, I'm happy to leave this open for a bit until you do. I just hit one on `gcc 8.5` in the `dmodex.c` example:
> 
> ```
> dmodex.c: In function ‘main’:
> dmodex.c:145:46: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
>      snprintf(proc.nspace, PMIX_MAX_NSLEN, "%s",  myproc.nspace);
>                                               ^
> dmodex.c:145:5: note: ‘snprintf’ output between 1 and 256 bytes into a destination of size 255
>      snprintf(proc.nspace, PMIX_MAX_NSLEN, "%s",  myproc.nspace);
> ```
> 
> Should be:
> 
> ```c
> PMIX_LOAD_NSPACE(proc.nspace, myproc.nspace);
> ```
> 
> to avoid the complaint.

Haha. I wasn't planning on committing the rest here because this one looked the scariest and I wanted it addressed first. That said, if you're okay with the other fixes going into this pull request, I'll prepare them and push them soon.

**Comment by rhc54** [comment]
> That said, if you're okay with the other fixes going into this pull request, I'll prepare them and push them soon.

Sure, go ahead - might as well get them all in one shot.

**Pull request merged**
