### PR TITLE
Checkpoint gds/shmem revamp.

### PR DESCRIPTION
**Pull request by samuelkgutierrez**
* Multi-node async reinit now works
* Performance improvements
* Bug fixes

Signed-off-by: Samuel K. Gutierrez <samuel@lanl.gov>

### CODE REVIEW

**Comment by samuelkgutierrez** [comment]
bot:ibm:retest

**Comment by samuelkgutierrez** [comment]
bot:ibm:retest

**Comment by samuelkgutierrez** [comment]
Looks like these tests are diffing for some reason:
```
16:03:14 Verify stdout/stderr for testcase attach-colaunch1
40,43d39
< daemon-0            : [@NS<3>:0:PID<?>] Sending release
< daemon-0            : [@NS<3>:0:PID<?>] Sending release
< daemon-0            : Waiting for application namespace @NS<2> to terminate
< daemon-0            : Waiting for application namespace @NS<2> to terminate
47a44,47
> daemon-0            : [@NS<3>:0:PID<?>] Sending release
> daemon-0            : [@NS<3>:0:PID<?>] Sending release
> daemon-0            : Waiting for application namespace @NS<2> to terminate
> daemon-0            : Waiting for application namespace @NS<2> to terminate
16:03:14 ERROR: testcase attach-colaunch1 stdout does not match baseline
```
```
16:03:27 Verify stdout/stderr for testcase attach-colaunch2
40,43d39
< daemon-0            : [@NS<3>:0:PID<?>] Sending release
< daemon-0            : [@NS<3>:0:PID<?>] Sending release
< daemon-0            : Waiting for application namespace @NS<2> to terminate
< daemon-0            : Waiting for application namespace @NS<2> to terminate
47a44,47
> daemon-0            : [@NS<3>:0:PID<?>] Sending release
> daemon-0            : [@NS<3>:0:PID<?>] Sending release
> daemon-0            : Waiting for application namespace @NS<2> to terminate
> daemon-0            : Waiting for application namespace @NS<2> to terminate
16:03:27 ERROR: testcase attach-colaunch2 stdout does not match baseline
```

**Comment by rhc54** [comment]
Looking at the error message, I think the problem is that the `attach` test is looking for output from a certain stage to appear on `stdout`, but it is appearing on `stderr` instead. I'll take a look at it.

**Comment by samuelkgutierrez** [comment]
Thank you, sir.

**Comment by rhc54** [comment]
I wouldn't worry about it for now - if this PR is otherwise ready to go, then let's commit it.

**Pull request merged**
