### PR TITLE
Handle string literals in environ to unblock hwloc versions

### PR DESCRIPTION
**Pull request by bwbarrett**
Address https://github.com/openpmix/openpmix/issues/2450 by being more robust about environ handling when merging environments for application launch.

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Review by rhc54 — APPROVED** [review]
LGTM! I haven't searched to see where else we touch the environment, so we may hit the "trip wire" again when broader experience is gained. At least we have tools we can use to fix that if/when it happens.

**Comment by bwbarrett** [comment]
@rhc54 I looked through every use of environ and this was the only place where we were directly mucking with environment strings (vs doing searches or just calling pmix_setenv(..., &environ).  So we should be ok.

**Comment by rhc54** [comment]
I can't tell if the PRRTE CI ran again or not - did anybody copy the timestamp on it before retest?

**Comment by rhc54** [comment]
Current test timestamp is `Fri Feb  4 16:27:13 EST 2022`

bot:ibm:prrte:retest

**Comment by rhc54** [comment]
Yeah, this looks like a true problem. My best guess is that something in the new `pmix_environ_merge_inplace` function is segfaulting when we try to locally "spawn".

**Comment by rhc54** [comment]
@bwbarrett Just to be clear - there is no problem in your new code. The only issue was a typo where you checked the return status from `pmix_environ_merge_inplace` - you had `==` instead of `!=`. So no need to adjust/add to the tests you wrote.

**Pull request merged**
