### PR TITLE
Added infrastructure to test_v2 suite to enable basic results-checking

### PR DESCRIPTION
**Pull request by cpshereda**
Also added infrastructure to pass values as encoded argument from server(s) to clients for validation purposes.

'test_params' and 'validation_params' structs will be merged into a single struct in a later commit.

### CODE REVIEW

**Comment by artpol84** [comment]
Looks good.
I'll create a counterpart issue for this test in pmix-test repo

**Comment by artpol84** [comment]
@cpshereda One thing that I'd personally like to see is the separation between infrastructural changes and the introduction of a new test.
It should be easy to do - let me know if you want to sync on how to do it quickly.
But logically those are 2 separate items and I prefer to have them as 2 separate commits.

**Comment by cpshereda** [comment]
@artpol84 This PR changed to infrastructure-only, per your request.

**Comment by artpol84** [comment]
I’ve actually asked to split the pr on 2 commits.
But this way works as well.

**Comment by cpshereda** [comment]
I'll do it that way next time.

**Pull request merged**
