### PR TITLE
Enable gds/shmem by default take 1.

### PR DESCRIPTION
**Pull request by samuelkgutierrez**
Let us see how a broader set of CI tests like gds/shmem.

Signed-off-by: Samuel K. Gutierrez <samuel@lanl.gov>

### CODE REVIEW

**Comment by rhc54** [comment]
Looks like we have a problem with ppc64:
```shell
[ci-pmix-gnu-upstream-cn-4:00051] PMIX ERROR: FILE_OPEN_FAILURE in file pmix_shmem.c at line 121
[ci-pmix-gnu-upstream-cn-4:00051] PMIX ERROR: FILE_OPEN_FAILURE in file gds_shmem.c at line 673
[ci-pmix-gnu-upstream-cn-4:00051] PMIX ERROR: FILE_OPEN_FAILURE in file gds_shmem.c at line 752
[ci-pmix-gnu-upstream-cn-4:00051] PMIX ERROR: FILE_OPEN_FAILURE in file gds_shmem.c at line 1495
[ci-pmix-gnu-upstream-cn-4:00051] PMIX ERROR: FILE_OPEN_FAILURE in file gds_shmem.c at line 1532
[ci-pmix-gnu-upstream-cn-4:00050] PMIX ERROR: FILE_OPEN_FAILURE in file pmix_shmem.c at line 121
[ci-pmix-gnu-upstream-cn-4:00050] PMIX ERROR: FILE_OPEN_FAILURE in file gds_shmem.c at line 673
[ci-pmix-gnu-upstream-cn-4:00050] PMIX ERROR: FILE_OPEN_FAILURE in file gds_shmem.c at line 752
[ci-pmix-gnu-upstream-cn-4:00050] PMIX ERROR: FILE_OPEN_FAILURE in file gds_shmem.c at line 1495
[ci-pmix-gnu-upstream-cn-4:00050] PMIX ERROR: FILE_OPEN_FAILURE in file gds_shmem.c at line 1532
[ci-pmix-gnu-upstream-cn-4:00050] PMIX ERROR: UNPACK-FAILURE in file gds_shmem.c at line 1556
```

**Comment by samuelkgutierrez** [comment]
> Looks like we have a problem with ppc64:

I noticed that. I'll need to take a closer look and probably add nicer error messages to see what's going on there. Fingers crossed you have an idea how to address the other CI  issues.

**Comment by rhc54** [comment]
I have the cross-version tests fixed now - as you can see since they are all passing 😄

**Comment by samuelkgutierrez** [comment]
Yes, thank you! I think I know why the IBM test is failing and will try to provide a fix ASAP.

**Comment by samuelkgutierrez** [comment]
bot:ibm:retest

**Comment by samuelkgutierrez** [comment]
bot:ibm:retest

**Comment by samuelkgutierrez** [comment]
I'm stumped, so any help is appreciated. The failure has shifted, but I don't know how to deal with this one:
```
=======================
Running init_finalize_pmix: prun --dvm-uri file:dvm.uri --num-connect-retries 1000 ./init_finalize_pmix
=======================
--------------------- Execution (init/finalize): 1
--------------------- Execution (init/finalize): 2
--------------------------------------------------------------------------
PRTE has lost communication with a remote daemon.

  HNP daemon   : [prte-ci-pmix-gnu-upstream-cluster-login-hrnn9-73416@0,0] on node ci-pmix-gnu-upstream-cluster-login-hrnn9
  Remote daemon: [prte-ci-pmix-gnu-upstream-cluster-login-hrnn9-73416@0,1] on node ci-pmix-gnu-upstream-cn-0

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
[ci-pmix-gnu-upstream-cluster-login-hrnn9:73416] UNSUPPORTED DAEMON ERROR STATE: FAILED TO START
[ci-pmix-gnu-upstream-cluster-login-hrnn9:73416] UNSUPPORTED DAEMON ERROR STATE: FAILED TO START
[ci-pmix-gnu-upstream-cluster-login-hrnn9:73416] UNSUPPORTED DAEMON ERROR STATE: FAILED TO START
[ci-pmix-gnu-upstream-cluster-login-hrnn9:73416] UNSUPPORTED DAEMON ERROR STATE: FAILED TO START
[ci-pmix-gnu-upstream-cluster-login-hrnn9:73416] UNSUPPORTED DAEMON ERROR STATE: FAILED TO START
```

**Comment by rhc54** [comment]
That usually means the daemons are segfaulting - I'll try to reproduce here. If I can't, then the only ways to debug are to (a) ask @jjhursey for assistance, and/or (b) try adding print statements to see where they fail.

**Comment by samuelkgutierrez** [comment]
Sounds good, @rhc54. Thank you.

**Comment by rhc54** [comment]
@samuelkgutierrez One point to look at: the test that is failing is the first one where we run multiple jobs against a persistent DVM. The most likely culprit, therefore, is the case where the server finalizes the shmem subsystem for one nspace, and then creates a second shmem space for the next nspace. I suspect something doesn't get cleaned up correctly and causes the second nspace operation to segfault.

**Comment by rhc54** [comment]
Okay, this is easy to replicate. Just run `prte` and then try to run two `prun` of any job that calls `PMIx_Init` (e.g., "examples/hello") and the daemons will crash. The segfault is here:
```shell
Thread 1 (Thread 0x7fb3df726700 (LWP 61649)):
#0  0x00007fb3e054cc98 in pmix_gds_shmem_check_session (job=0x7fb3d80a6320, sid=4294967295, create=true) at gds_shmem_utils.c:112
#1  0x00007fb3e0558f93 in store_session_array (job=0x7fb3d80a6320, val=0x7fb3d80b24d0) at gds_shmem_store.c:408
#2  0x00007fb3e0559b2f in pmix_gds_shmem_store_local_job_data_in_shmem (job=0x7fb3d80a6320, job_data=0x7fb3df725270) at gds_shmem_store.c:542
#3  0x00007fb3e054a702 in server_register_new_job_info (peer=0x7fb3d806c690, reply=0x7fb3d8078980) at gds_shmem.c:1376
#4  0x00007fb3e054ad68 in server_register_job_info (peer_struct=0x7fb3d806c690, reply=0x7fb3d8078980) at gds_shmem.c:1443
#5  0x00007fb3e4abe349 in server_switchyard (peer=0x7fb3d806c690, tag=101, buf=0x7fb3df725c70) at server/pmix_server.c:4614
#6  0x00007fb3e4ac4c44 in pmix_server_message_handler (pr=0x7fb3d806c690, hdr=0x7fb3d807a474, buf=0x7fb3df725c70, cbdata=0x0) at server/pmix_server.c:4932
#7  0x00007fb3e4be270c in pmix_ptl_base_process_msg (fd=-1, flags=4, cbdata=0x7fb3d807a340) at base/ptl_base_sendrecv.c:839
#8  0x00007fb3e45e3b11 in event_process_active_single_queue (base=base@entry=0x804c60, activeq=0x805090, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0)
    at event.c:1691
#9  0x00007fb3e45e41ef in event_process_active (base=0x804c60) at event.c:1783
#10 event_base_loop (base=0x804c60, flags=1) at event.c:2006
#11 0x00007fb3e4afd808 in progress_engine (obj=0x804b40) at runtime/pmix_progress_threads.c:228
#12 0x00007fb3e3a4fea5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007fb3e3778b0d in clone () from /lib64/libc.so.6
(gdb) list
107	        bool found = false;
108	        // No session has been assigned to this job. See
109	        // if the given ID has already been registered.
110	        pmix_gds_shmem_session_t *si;
111	        PMIX_LIST_FOREACH(si, &comp->sessions, pmix_gds_shmem_session_t) {
112	            if (si->session == sid) {
113	                found = true;
114	                break;
115	            }
116	        }
(gdb) print si
$1 = (pmix_gds_shmem_session_t *) 0x3fd9d0031448
(gdb) print *si
Cannot access memory at address 0x3fd9d0031448
```
It looks like the `&comp->sessions` list has been corrupted?

**Comment by samuelkgutierrez** [comment]
Great help! Thank you very much, @rhc54. I'll take a look to see what's going wrong there.

**Comment by samuelkgutierrez** [comment]
@rhc54, thanks to your help I found the problem. I just need to find a nice way of dealing with it. I'm going to push a modification that I think will fix the crash, but it is problematic because I think it leaks memory.

Please do not merge if all the tests pass. This is just for testing. Thank you!

**Comment by rhc54** [comment]
no problem - just updating status. Won't merge until you give the "all clear"!

**Comment by samuelkgutierrez** [comment]
Test 1 is complete. We have some work to do.

**Pull request closed without merging**
