### PR TITLE
Silence Coverity warning

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
The last CI run failed with [this](https://gist.github.com/ibm-ompi/5273362a988c5d34619a4ac308a270b4) log and the message:
 > Could not connect to prte at nspace 134.59674.1: UNREACHABLE

@rhc54 is that the type of failure you were mentioning in https://github.com/openpmix/prrte/issues/448 ?

bot:ibm:prrte:retest

**Comment by rhc54** [comment]
Yes, that's what I see every now and then

**Comment by jjhursey** [comment]
Huh. That time the prun wrapper test (mpirun-like) just hung for 5 minutes. We can try it again, but I wonder if the race in in that mode.
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
The PRRTE run failed again on a timeout with the prun wrapper test. We can try again, but I don't think this PR is causing the issue. Since it seems to be failing only on the that unit test it might be a place to focus for reproducing.
bot:ibm:prrte:retest

**Pull request merged**
