### PR TITLE
Use newer config.guess / config.sub files when relevant

### PR DESCRIPTION
**Pull request by rhc54**
Refs https://github.com/open-mpi/ompi/issues/8410

This is the PMIx equivalent of https://github.com/open-mpi/ompi/pull/8417

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
ONe this gets the :+1: then we can copy it into PRRTE

**Review by jsquyres — APPROVED** [review]
I squashed+force pushed two minor updates:

1. s/Open MPI/OpenPMIx/ in README.md.
2. Made the 2 `upstream-*` files be executable.  Otherwise, `autogen.pl` can't execute them to get their timestamps, the file files don't end up getting replaced in the tree.

**Comment by rhc54** [comment]
Thanks!

**Comment by rhc54** [comment]
Poor Travis - we knew him well.

**Pull request merged**
